### ISSUE TITLE
DNS Issue When Starting homebridge

### ISSUE THREAD

**Issue by boojew** [oznu/docker-homebridge#5]
I have the docker container installed, but when it starts, homebridge crashes with the following

{"log":"/usr/local/share/.config/yarn/global/node_modules/mdns/lib/advertisement.js:56\n","stream":"stderr","time":"2017-07-04T03:51:35.236638739Z"}
{"log":"  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,\n","stream":"stderr","time":"2017-07-04T03:51:35.236670538Z"}
{"log":"         ^\n","stream":"stderr","time":"2017-07-04T03:51:35.236676538Z"}
{"log":"\n","stream":"stderr","time":"2017-07-04T03:51:35.236681638Z"}
{"log":"Error: dns service error: unknown\n","stream":"stderr","time":"2017-07-04T03:51:35.236686638Z"}
{"log":"    at Error (native)\n","stream":"stderr","time":"2017-07-04T03:51:35.236691638Z"}
{"log":"    at new Advertisement (/usr/local/share/.config/yarn/global/node_modules/mdns/lib/advertisement.js:56:10)\n","stream":"stderr","time":"2017-07-04T03:51:35.236714838Z"}
{"log":"    at Object.create [as createAdvertisement] (/usr/local/share/.config/yarn/global/node_modules/mdns/lib/advertisement.js:64:10)\n","stream":"stderr","time":"2017-07-04T03:51:35.236720938Z"}
{"log":"    at Advertiser.startAdvertising (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Advertiser.js:43:30)\n","stream":"stderr","time":"2017-07-04T03:51:35.236737238Z"}
{"log":"    at Bridge.Accessory._onListening (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:532:20)\n","stream":"stderr","time":"2017-07-04T03:51:35.236742638Z"}
{"log":"    at emitOne (events.js:96:13)\n","stream":"stderr","time":"2017-07-04T03:51:35.236747638Z"}
{"log":"    at HAPServer.emit (events.js:188:7)\n","stream":"stderr","time":"2017-07-04T03:51:35.236752538Z"}
{"log":"    at HAPServer._onListening (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/HAPServer.js:190:8)\n","stream":"stderr","time":"2017-07-04T03:51:35.236757338Z"}
{"log":"    at emitOne (events.js:96:13)\n","stream":"stderr","time":"2017-07-04T03:51:35.236762438Z"}
{"log":"    at EventedHTTPServer.emit (events.js:188:7)\n","stream":"stderr","time":"2017-07-04T03:51:35.236767038Z"}

Looks like its complaining that DNS registration is failing, but works fine for a non-docker instance of homebridge. 

I have no clue what this actually is try

**Comment by oznu** [comment]
What platform are you running on?

**Comment by boojew** [comment]
Ubuntu 17.04

**Comment by oznu** [comment]
I think this is caused by multiple instances of the avahi running, possibly in other containers you have running or on the same host. 

I have a solution that I *think* might solve your problem that I will push shortly.

**Comment by oznu** [comment]
Can you give this image try and let me know if it resolves the issue?

```
docker run --net=host oznu/homebridge:avahi-fix
```

Thanks.

**Comment by boojew** [comment]
YES! That seems to have done it! Thanks so much!

**Comment by boojew** [comment]
Actually, maybe I spoke to soon. When I do the initial run - it works;
however if I stop and restart the container, I run into the same issue
again.

**Comment by oznu** [comment]
Thanks for testing out that tag for me. I've now fixed the container restart issue as well, it was a bit of regression from the last lot of major changes I made.

You can swap back to using the ```latest``` tag as I'll be deleting the ```avahi-fix``` tag.

New release: https://github.com/oznu/docker-homebridge/releases/tag/1.1.1

If you're still having issues feel free to reopen this issue.

**Comment by boojew** [comment]
Just tested with the latest tag, and I am still having the same issue :(

**Comment by oznu** [comment]
Strange. Do you mind posting the full log output after you restart the container?

```
docker logs <container id or name>
```

**Comment by boojew** [comment]
Interesting.. I use docker stop exclusively; however, I have been using docker start and not docker run to start the container again. It was my understanding that docker run would build out a new container each time

**Comment by oznu** [comment]
I've merged that pull request and the builds have finished. Would you mind testing the `latest` tag again?

```
docker pull oznu/homebridge:latest
```

Thanks again for helping me debug this one.

**Comment by boojew** [comment]
Yea, this seems to be fully resolved now! Thanks
